spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE